# config.py

# Plotting settings
DEFAULT_PLOT_COLOR = "#1f77b4"
DEFAULT_GRID_STYLE = "--"
DEFAULT_LINE_WIDTH = 2

# Default values for labs
DEFAULT_POLY_COEFFS = "1, -2, 1"
DEFAULT_TRIG_FUNCTION = "sin"
DEFAULT_AMPLITUDE = 1.0
DEFAULT_FREQUENCY = 1.0
DEFAULT_PHASE_SHIFT = 0.0
DEFAULT_EXP_LOG_FUNCTION = "Exponential"
DEFAULT_BASE = 2.0
